name: CI Pipeline

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar pytest
        run: pip install pytest

      - name: Rodar testes
        run: pytest

      - name: Rodar script
        run: python app.py
        
      - name: Notificar Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🚀 Novo evento no repositório!\"}" \
          ${{ secrets.DISCORD_WEBHOOK }}
